project:
  type: website

website:
  title: "Jinxiong You"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/jinxyou
      - icon: instagram
        href: https://instagram.com/eugeneuuuu
      - icon: linkedin
        href: https://linkedin.com/in/jinxyou
      - icon: facebook
        href: https://www.facebook.com/eugeneuuuu

format:
  html:
    theme: default
    css: styles.css
    toc: true



